In [6]:
import numpy as np
students = np.random.randint(50,101,size=(50,5))
students

array([[ 83,  83,  78,  63,  64],
       [ 94, 100,  67,  80,  64],
       [ 98,  82,  79,  64,  87],
       [ 76,  50,  91,  52,  60],
       [ 62,  53,  86,  79,  59],
       [ 95,  79,  54,  50,  92],
       [ 53,  93,  92,  81,  62],
       [ 51,  86,  51,  93,  63],
       [ 69,  63,  54,  52,  61],
       [ 85,  86,  58,  96,  65],
       [ 52,  61,  82,  78,  95],
       [ 90,  83,  72,  74,  64],
       [ 69,  68,  99,  73,  51],
       [ 73,  76,  87,  83,  64],
       [ 89,  61,  52,  59,  75],
       [ 91,  56,  96,  84,  78],
       [ 84,  69,  65,  96,  81],
       [ 57,  93,  55,  66,  88],
       [ 53,  77,  80,  80,  98],
       [ 64,  50,  63,  95,  79],
       [ 94,  79,  81,  85,  94],
       [ 87,  81,  70,  56,  76],
       [ 92,  94,  99,  70,  91],
       [ 57,  54,  96,  70,  82],
       [ 69,  99,  56,  99,  86],
       [ 90,  50,  73,  61,  98],
       [ 95,  74,  87,  71,  73],
       [ 96,  75,  87,  62,  63],
       [ 87,  87,  51,  96,  76],
       [ 51,  

In [13]:
students[0,0]
students[:1,:]
students[:1] #前一個學生
students[:2] #前2個學生
students[-5:] #最後5個學生

array([[60, 51, 71, 61, 90],
       [56, 62, 90, 76, 61],
       [69, 74, 54, 91, 74],
       [59, 75, 64, 60, 98],
       [57, 94, 57, 84, 98]])

In [16]:
students[:,0] #第一科所有分數
students[:,-1] #最後一科所有分數

array([64, 64, 87, 60, 59, 92, 62, 63, 61, 65, 95, 64, 51, 64, 75, 78, 81,
       88, 98, 79, 94, 76, 91, 82, 86, 98, 73, 63, 76, 86, 59, 73, 99, 99,
       56, 83, 79, 50, 91, 77, 60, 52, 84, 78, 95, 90, 61, 74, 98, 98])

In [22]:
np.sum(students[:1]) #第一個學生總分
np.sum(students[:2],axis=1) #前2個學生的總分 
np.sum(students,axis=1) #全班每位學生的總分
np.mean(students,axis=0) #每一科全班的平均
np.median(students,axis=0) #每一科全班的中位數

array([71. , 75. , 72.5, 78. , 77.5])